"""add relationships and foreign keys

Revision ID: 64bd30b495a3
Revises: f2a25fb5e334
Create Date: 2026-01-04 17:11:36.821863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bd30b495a3'
down_revision = 'f2a25fb5e334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_mood_categories',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('mood_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mood_category_id'], ['mood_categories.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'mood_category_id')
    )
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_affiliate_links_movie_id', 'movies', ['movie_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_comments_movie_id', 'movies', ['movie_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_favorites_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_favorites_movie_id', 'movies', ['movie_id'], ['id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_ratings_movie_id', 'movies', ['movie_id'], ['id'])
        batch_op.create_foreign_key('fk_ratings_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_suggestions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_suggestions_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ratings_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_ratings_movie_id', type_='foreignkey')
        batch_op.drop_column('movie_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorites_movie_id', type_='foreignkey')
        batch_op.drop_constraint('fk_favorites_user_id', type_='foreignkey')
        batch_op.drop_column('createdAt')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_comments_movie_id', type_='foreignkey')
        batch_op.drop_column('movie_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_constraint('fk_affiliate_links_movie_id', type_='foreignkey')
        batch_op.drop_column('movie_id')

    op.drop_table('movie_mood_categories')
    # ### end Alembic commands ###
